### ISSUE TITLE
Insert when missing: duplicate attribute errors

### ISSUE THREAD

**Issue by SeriousM** [BMuuN/vsts-assemblyinfo-task#53]
When patching AssemblyInfo.cs and *.csproj (core) with "Insert when missing" enabled I get some errors that attributes are declared multiple times.

The mechanism should take care about this problem.

In addition sometimes the using `using System.Reflection;` and `using System.Runtime.CompilerServices;` are missing in the AssemblyInfo.cs.
I've patched the script to include it for csharp: https://github.com/SeriousM/vsts-assemblyinfo-task/blob/0697787f5323b80e07554c651e1527dcf67597c0/src/task/NetFramework.ps1

**Comment by BMuuN** [comment]
Thanks for the feedback @SeriousM.  Your contributions have been reference in the release notes! 

We've implemented your request in v2.0.65.  Please accept our sincere apologies for the delay implementing this change.

Please note this upgrade is a breaking change and you should follow these steps to prevent any down-time:  https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

This issue will now be closed.  If you feel the issue has not been fixed please feel free to re-open the issue.

**Comment by SeriousM** [comment]
Thank you very much!

**Comment by FixRM** [comment]
Hello! Still getting Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute for plugin project in this repository: https://github.com/FixRM/LastSchedule. I tried both: update AssemlyInfo and project file.
