### ISSUE TITLE
Adding Imports alphabetical order

### ISSUE THREAD

**Issue by davidmiguelalves** [BMuuN/vsts-assemblyinfo-task#86]
This task add's some imports i.e. "using System.Runtime.CompilerServices" and if you have code analysis in your csproj this using isn't added correctly, and build fails:
[image](https://ibb.co/jRnsvdT)
"Using directives must be ordered alphabetically by the namespaces."

Can u add this using's correctly?

Thanks
David Miguel Alves

**Comment by BMuuN** [comment]
Fixed with v2.1.98

**Comment by angelwang** [comment]
i am still seeing this issue with latest version. 2.3.105. Did i miss anything?

**Comment by BMuuN** [comment]
Hey @angelwang the task cannot add using statement in alphabetical order.  To ensure using statements are in the correct order you'll need to add all statements to your Assembly Info file before committing to Azure DevOps.
